#ifndef NVIC_CONFIG_H
#define NVIC_CONFIG_H

/*Options:
    GRP_4_SUB_0_BITS
    GRP_3_SUB_1_BITS
    GRP_2_SUB_2_BITS
    GRP_1_SUB_3_BITS
    GRP_0_SUB_4_BITS
*/

#define NVIC_GRP_SUB_DISTRIBUTION           GRP_2_SUB_2_BITS

#endif